### ISSUE TITLE
RBAC premissions required

### ISSUE THREAD

**Issue by ChristopherL-STCU** [microsoft/azure-app-configuration-se-extension#4]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest) and the [latest version of the Azure App Configuration extension for Storage Explorer](https://github.com/Microsoft/azure-app-configuration-se-extension/releases/latest).
- [X] I have checked existing resources in this repository.
- [X] I have searched for [similar issues](https://github.com/microsoft/azure-app-configuration-se-extension/issues).

### Storage Explorer Version

1.25.1

### Azure App Configuration extension Version

0.1.0

### Architecture

x64

### Storage Explorer Build Number

20220809.7

### Platform

Windows

### OS Version

Windows 10

### Bug Description

I installed the extension. I can see the App Config instance. When I click on the instance to view its contents I receive the error:

> Please verify if you have the rbac permissions to access the resources in this App Configuration store.
```
{
  "name": "RestError",
  "message": "",
  "statusCode": 403,
  "request": {
    "url": "https://myappconfig.azconfig.io/kv?api-version=1.0",
    "headers": {
      "accept": "application/vnd.microsoft.appconfig.kvset+json, application/json, application/problem+json",
      "accept-encoding": "gzip,deflate",
      "user-agent": "Microsoft Azure Storage Explorer/1.25.1 (win32) azsdk-js-app-configuration/1.4.0-beta.1 core-rest-pipeline/1.9.0 Node/v16.14.2 OS/(ia32-Windows_NT-10.0.19044)",
      "x-ms-client-request-id": "df5003f9-f88a-41e1-b352-83dd5446d43d",
      "authorization": "Bearer JSON Web Token Redacted"
    },
    "method": "GET",
    "timeout": 0,
    "disableKeepAlive": false,
    "streamResponseStatusCodes": {},
    "withCredentials": false,
    "tracingOptions": {
      "tracingContext": {
        "_contextMap": {}
      }
    },
    "requestId": "df5003f9-f88a-41e1-b352-83dd5446d43d",
    "allowInsecureConnection": true,
    "enableBrowserStreams": false
  },
  "response": {
    "status": 403,
    "headers": {
      "server": "openresty/1.17.8.2",
      "date": "Wed, 31 Aug 2022 23:45:11 GMT",
      "content-length": "0",
      "connection": "keep-alive",
      "x-ms-request-id": "adad24dd-69de-41b9-b80e-662da2365fd9",
      "x-ms-correlation-request-id": "adad24dd-69de-41b9-b80e-662da2365fd9",
      "access-control-allow-origin": "*",
      "access-control-allow-credentials": "true",
      "access-control-expose-headers": "DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-useragent, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, retry-after-ms, x-ms-request-id, x-ms-client-session-id, x-ms-effective-locale, WWW-Authenticate, traceparent, tracestate",
      "strict-transport-security": "max-age=15724800; includeSubDomains"
    },
    "request": {
      "url": "https://myappconfig.azconfig.io/kv?api-version=1.0",
      "headers": {
        "accept": "application/vnd.microsoft.appconfig.kvset+json, application/json, application/problem+json",
        "accept-encoding": "gzip,deflate",
        "user-agent": "Microsoft Azure Storage Explorer/1.25.1 (win32) azsdk-js-app-configuration/1.4.0-beta.1 core-rest-pipeline/1.9.0 Node/v16.14.2 OS/(ia32-Windows_NT-10.0.19044)",
        "x-ms-client-request-id": "df5003f9-f88a-41e1-b352-83dd5446d43d",
        "authorization": "Bearer JSON Web Token Redacted"
      },
      "method": "GET",
      "timeout": 0,
      "disableKeepAlive": false,
      "streamResponseStatusCodes": {},
      "withCredentials": false,
      "tracingOptions": {
        "tracingContext": {
          "_contextMap": {}
        }
      },
      "requestId": "df5003f9-f88a-41e1-b352-83dd5446d43d",
      "allowInsecureConnection": true,
      "enableBrowserStreams": false
    },
    "bodyAsText": ""
  },
  "details": {}
}
```

I can view the App Config contents in the Portal. IAM shows I am a Contributor. There could be network restrictions in place which is interfering with the request, although I'd expect a different response back if that is the case. Is there a way we can troubleshoot this further?

### Steps to Reproduce

1. Launch Storage Explorer
2. Expand App Configurations node
3. Click on an App Configuration instance

### Actual Experience

403 HTTP Status code returned

### Expected Experience

View the contents of the App Config instance

**Comment by JasonYeMSFT** [comment]
@ChristopherL-STCU You will need an RBAC role such as "App Configuration Data Owner/Reader" to be able to read the contents in your App Configuration store. In the error dialog there should be a link that directly goes to the permission management page of your store so you can directly configure it there.

**Comment by JasonYeMSFT** [comment]
@ChristopherL-STCU Did you have a chance to check your RBAC permissions?

**Comment by ChristopherL-STCU** [comment]
Thank you for the follow up @JasonYeMSFT. Here are what my role assignments are for the resource:

![image](https://user-images.githubusercontent.com/22223998/192865680-9afa057d-3cbe-4690-a37f-a7f31a588c82.png)

**Comment by JasonYeMSFT** [comment]
As I said, you can add "App Configuration Data Owner" or "App Configuration Data Reader" role to grant you access to App Configuration data. Although many roles say it grants you access to "all" resources, many of them refers to "ARM" resources on Azure (e.g. Storage Account, Subscriptions, etc.). Data access such as storage, app configuration, etc. need their own permissions.

**Comment by ChristopherL-STCU** [comment]
Okay. Unfortunately I won't be able to verify this in this subscription. But thank you, I'll know what to do if I experience this elsewhere, where I have the ability to be added to other roles. I'll close this now.
