### ISSUE TITLE
Where's the code?

### ISSUE THREAD

**Issue by andrewksmith** [microsoft/azure-app-configuration-se-extension#5]
At the risk of having missed the obvious...where is the code?

**Comment by JasonYeMSFT** [comment]
Thanks for asking. Unfortunately we haven't convinced the management team to open source it so far. Your vote will be very helpful for us to continue the conversation with them to revisit this topic. I will close this issue and link it with https://github.com/microsoft/azure-app-configuration-se-extension/issues/8 for the ease of tracking.
