### ISSUE TITLE
To add "tags" attribute into add and view as column

### ISSUE THREAD

**Issue by eissko** [microsoft/azure-app-configuration-se-extension#6]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest) and the [latest version of the Azure App Configuration extension for Storage Explorer](https://github.com/Microsoft/azure-app-configuration-se-extension/releases/latest).
- [X] I have checked existing resources in this repository.
- [X] I have searched for [similar issues](https://github.com/microsoft/azure-app-configuration-se-extension/issues).

### Problem

To add "tags" attribute into add and view as column. Each item in app configuration can contain the list of key/value pairs as tags. It would be perfect to support the tags as input in storage explorer when adding new item.  Also when viewing app configurations have the column tags visible.

### Desired Solution

To add "tags" attribute into add and view as column

**Comment by JasonYeMSFT** [comment]
Extension v0.2.0 has been published to add tags to the data table view. It also allows editing the tags of a key-value in an Edit Tags dialog.
