### ISSUE TITLE
To add the functionality of filtering the app config items by key, label and tags

### ISSUE THREAD

**Issue by eissko** [microsoft/azure-app-configuration-se-extension#7]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest) and the [latest version of the Azure App Configuration extension for Storage Explorer](https://github.com/Microsoft/azure-app-configuration-se-extension/releases/latest).
- [X] I have checked existing resources in this repository.
- [X] I have searched for [similar issues](https://github.com/microsoft/azure-app-configuration-se-extension/issues).

### Problem

To add the functionality of filtering the app config items by key, label and tags

### Desired Solution

To add the functionality of filtering the app config items by key, label and tags

**Comment by JasonYeMSFT** [comment]
Extension v0.2.0 has been published. It adds the capability to filter key-values by key and labels. Unfortunately the service doesn't support filtering key-values by tags right now. We can look into it in the future after we sync up with the service team. https://github.com/microsoft/azure-app-configuration-se-extension/issues/9
